# Generated by Django 2.1.15 on 2024-03-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemModules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('parentid', models.CharField(max_length=128, null=True)),
                ('module_type', models.CharField(max_length=16, null=True)),
                ('event_code', models.CharField(max_length=128, null=True)),
                ('visibility', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('role', models.CharField(max_length=255)),
                ('access', models.CharField(max_length=255)),
                ('route_access', models.CharField(max_length=255)),
                ('is_resetpwd', models.BooleanField(default=True)),
                ('systemmodule', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'auth_users',
            },
        ),
    ]
