RESPONSE_MESSAGE_CONSTANTS = {
    'EMPTY_RESPONSE_MESSAGE_PLACEHOLDER' : 'The request completed successfully',
    'SERVER_ERROR_RESPONSE_MESSAGE' : "The request not completed. it's not you it's me",
    'EVENT_ID_CANT_BE_EMPTY' : "Event Id can't be empty",
    'USER_CANT_BE_EMPTY' : "User Id can't be empty",
    'EVENT_DESCREPTION_CANT_BE_EMPTY' : "Event description can't be empty",
    'EVENT_PAGE_PATH_CANT_BE_EMPTY' : "Event Page Path can't be empty",
    'EVENT_PAGE_NAME_CANT_BE_EMPTY' : "Event Page Name can't be empty",
    'EVENT_ADDED_SUCCESSFULLY' : "Event added for user successfully",
    'EVENT_FETCHED_SUCCESSFULLY' : "Event fetched successfully",
    "PAGE_NUMBER_CANT_BE_GREATER_THAN_RECORDS": "Requested page number is greater than the actual records",
    "INVALID_REQUESTS_ARGUMENTS": "Invalid Request",
    "ALERT_SETTINGS_FETCHED_SUCCESSFULLY": "Alert settings fetched successfully",
    "ALERT_SETTINGS_UPDATED_SUCCESSFULLY": "Alert settings updated successfully",
    "ALERT_LABEL_NOT_FOUND": "Alert label not found",
    "ALERT_USER_ID_NOT_FOUND": "User Id can't be empty",
    "ALERT_THRESHOLD_LIMIT_NOT_FOUND": "Threshold limit can't be empty",
    "QUERY_ERROR": "Error Occured in the Query",
    "START_DATE_CANT_BE_EMPTY": "Start date can't be empty",
    "END_DATE_CANT_BE_EMPTY": "End date can't be empty",
    "UNAUTHORIZED_REQUEST_MESSAGE": "You are Logged out from the system, please Login again",
    "ALERT_TIMESTAMP_NOT_FOUND": "No Alert read Timestamp was found",
    "USER_EMAIL_NOT_FOUND": "No User email was found",
    "PREFERENCES_UPDATED_SUCCESSFULLY": "Preferences are updated successfully",
    "PREFERENCES_DELETED_SUCCESSFULLY": "Preferences are Deleted successfully",
    "DATA_EDITED_AND_PUSHED_SUCCESSFULLY": "Data is pushed into Database",
    "DATA_EDITED_AND_PUSHED_FAILED": "Error encountered to push into Database",
}
